# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://yanghongfei.github.io
date_format: "ordinal"
title: Hi, I'm Yangxiaofei
subtitle: "一无所知的世界走下去才会有惊喜！"
description: "Hi, I'm Yangxiaofei"
keywords: 杨红飞, Yangxiaofei, Yanghongfei, Fred Yang
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 6

# ---------------- #
#      Author      #
# ---------------- #
author: Yanghongfei
organization: 
organization_url: 
github_username: yanghongfei
location: Shangqiu, HeNan 
email: yanghongfei97@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: opendevops-cn/opendevops

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: yanghongfei
    repo: yanghongfei.github.io
    oauth:
        client_id: 968bf991844521775a64
        client_secret: 5129b9167f19eaf20c405e13d1ff477485ec477a
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: yanghongfei
    repo: yanghongfei.github.io
    clientID: 968bf991844521775a64
    clientSecret: 5129b9167f19eaf20c405e13d1ff477485ec477a
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
